# Generated by Django 3.0.4 on 2020-03-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'CARGO',
                'verbose_name_plural': 'CARGOS',
            },
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name': 'SERVIÇOSS', 'verbose_name_plural': 'SERVICES'},
        ),
    ]
