# Generated by Django 3.0.4 on 2020-03-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200312_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('caracteristica', models.CharField(max_length=100, verbose_name='Feature')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Laptop'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folhas'), ('lni-layers', 'Camadas')], max_length=20, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Features',
                'verbose_name_plural': 'CARACTERÍSTICAS',
            },
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'FUNCIONÁRIOS'},
        ),
    ]
