# Generated by Django 3.0.2 on 2020-01-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço:')),
                ('estoque', models.IntegerField(verbose_name='Quantidade em estoque:')),
            ], # configurações do banco de dados, cada atributo na classe tem um id no banco de dados
        ),
    ]
