# Generated by Django 3.0.5 on 2020-04-15 01:54

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criação', models.DateField()),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('tem_estoque', models.BooleanField(default=True, verbose_name='Tem em Estoque?')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Veículo')),
                ('marcas', models.TextField(max_length=15, verbose_name='Marca')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano de Fabricação')),
                ('modelo', models.CharField(max_length=5, verbose_name='Ano do Modelo')),
                ('motorizacao', models.CharField(max_length=10, verbose_name='Motorização')),
                ('quilometragem', models.CharField(max_length=6, verbose_name='Quilometragem')),
                ('preco', models.CharField(max_length=10, verbose_name='Preço')),
                ('estado', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado')], max_length=20, verbose_name='Estado')),
                ('imagem', stdimage.models.StdImageField(upload_to=core.models.get_file_path)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'CARROS',
            },
        ),
    ]
