# Generated by Django 2.2.9 on 2020-06-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='status',
            field=models.CharField(default='#', max_length=20),
        ),
    ]
