# Generated by Django 2.2.9 on 2020-06-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admin_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Person'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
    ]
