# Generated by Django 2.2.9 on 2020-06-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200622_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(default='AGE', max_length=3),
        ),
    ]
