# Generated by Django 2.2.9 on 2020-06-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
