# Generated by Django 2.2.9 on 2020-04-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('nome', models.CharField(max_length=20, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'MARCAS',
            },
        ),
    ]
