# Generated by Django 2.2.9 on 2020-04-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificacao', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano de Fabricação')),
                ('anomodelo', models.CharField(max_length=4, verbose_name='Ano de Modelo')),
                ('quilometragem', models.CharField(max_length=7, verbose_name='Quilometragem')),
                ('estado', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado')], max_length=10, verbose_name='Estado')),
                ('preco', models.CharField(max_length=7, verbose_name='Preço')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Carros',
                'verbose_name_plural': 'CARROS',
            },
        ),
    ]
