# Generated by Django 2.2.9 on 2020-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carro_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='motor',
            field=models.CharField(default='#', max_length=3, verbose_name='Motorização'),
        ),
    ]
