# Generated by Django 2.2.9 on 2020-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carro_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='cambio',
            field=models.CharField(choices=[('Automático', 'Automático'), ('Manual', 'Manual')], default='#', max_length=15, verbose_name='Câmbio'),
        ),
    ]
