# Generated by Django 2.2.9 on 2020-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200529_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrators',
            name='text',
            field=models.TextField(default='', max_length=200, verbose_name='Texto'),
        ),
    ]
