# Generated by Django 2.2.9 on 2020-05-29 19:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_administrators_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrators',
            new_name='Admins',
        ),
    ]
