# Generated by Django 2.2.9 on 2020-06-02 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20200529_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10, verbose_name='Country')),
                ('state', models.CharField(max_length=15, verbose_name='State')),
            ],
        ),
        migrations.AlterField(
            model_name='admins',
            name='bio',
            field=models.TextField(default='', max_length=200, verbose_name='Bio'),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(help_text='01/01/2020', max_length=8, verbose_name='Birthday')),
                ('id_number', models.CharField(help_text='3141199', max_length=7, verbose_name='Id Number')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Employees',
                'verbose_name_plural': 'Employeess',
            },
        ),
    ]
