# Generated by Django 2.2.9 on 2020-06-03 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200603_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name'),
        ),
    ]
