# Generated by Django 2.2.9 on 2020-06-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200603_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
