# Generated by Django 2.2.9 on 2020-06-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_address_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AlterField(
            model_name='employees',
            name='birthday',
            field=models.CharField(help_text='01/01/2020', max_length=10, verbose_name='Birthday'),
        ),
    ]
