# Generated by Django 2.2.9 on 2020-06-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200603_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='', max_length=12),
        ),
    ]
