# Generated by Django 2.2.9 on 2020-06-03 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200603_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='Name'),
        ),
    ]
